version: "3"

services:
  comments:
    build:
      context: .
    ports:
      - "8001:8000"
    volumes:
      - ./:/comments
    command: >
      sh -c "python3 manage.py wait_for_db &&
             python3 manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=comments
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=comments
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
